version: "3.8"
services:
    api:
        container_name: laravel
        image: serversideup/php:8.1-fpm-nginx
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        environment:
            SSL_MODE: "off"
            PUID: 1000
            PGID: 1000
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=tdd
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - db-data:/var/lib/mysql
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379
    phpmyadmin:
        image: phpmyadmin
        depends_on:
        - database
        restart: always
        ports:
        - 8081:80
        environment:
        - PMA_ARBITRARY=1
volumes:
    db-data: ~
